update

diff --git a/.github/workflows/Master_build_new.yaml b/.github/workflows/Master_build_new.yaml
--- a/.github/workflows/Master_build_new.yaml
+++ b/.github/workflows/Master_build_new.yaml
@@ -36,9 +36,23 @@ jobs:
           pip install -r Dependencies/requirements.txt
           pip install reportlab pyinstaller qrcode
 
+      - name: Debug directory structure
+        run: |
+          dir
+          dir Code
+
+      - name: Verify CKD_core.py exists
+        run: |
+          if not exist "Code\CKD_core.py" (
+            echo "CKD_core.py not found!"
+            exit 1
+          ) else (
+            echo "CKD_core.py found."
+          )
+
       - name: Build with PyInstaller (Windows)
         run: |
-          python -m PyInstaller --onefile --name=NephroPath_win_pdf --icon=Dependencies/NephroPath_installer_icon.ico --add-data "Code/CKD_core.py;." --add-data "Code/CKD_pdf_files_new.py;." --add-data "Dependencies;Dependencies" --add-data "EMIS_Files;EMIS_Files" Code/CKD_Master_pdf_exefree.py
+          python -m PyInstaller --onefile --name=NephroPath_win_pdf --icon=Dependencies/NephroPath_installer_icon.ico --add-data "Code/CKD_core.py;." --add-data "Code/CKD_pdf_files_new.py;." --add-data "Dependencies;Dependencies" --add-data "EMIS_Files;EMIS_Files" --hidden-import CKD_pdf_files_new Code/CKD_Master_pdf_exefree.py
 
       - name: Move release
         run: |
