Update windows.yml

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -28,6 +28,12 @@ jobs:
         run: |
           Move-Item dist\NephroPath.exe .\NephroPath.exe -Force
 
+      - name: Test NephroPath.exe
+        run: |
+          .\NephroPath.exe  # Execute the file
+          if (!$?) { exit 1 }  # Exit with error if the executable fails
+          shell: pwsh  # Use PowerShell for scripting
+
       - name: Set up Git
         run: |
           git config --global user.email "nicholas.killough@outlook.com"
